server:
  port: 8085
spring:
  application:
    name: rydo-location-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Optional: connection pool tuning
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      pool-name: RydoHikariPool
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update   # options: none | validate | update | create | create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE